### ISSUE TITLE
socket and TLS options for eredis_sub

### ISSUE THREAD

**Issue by e-kmisk** [Nordix/eredis#47]
It seems that the `eredis_sub` module does not accept `socket_options`, unlike regular `eredis`.

As discussing in https://github.com/Nordix/eredis_cluster/issues/59 we are trying to use custom TCP socket options to handle disconnections, but it looks like this module will always use the hardcoded default socket options from `eredis.hrl`. TLS for example also does not seem possible to configure, as only the following options are used:
```erlang
    Host           = proplists:get_value(host, Args, "127.0.0.1"),
    Port           = proplists:get_value(port, Args, 6379),
    Password       = proplists:get_value(password, Args, ""),
    ReconnectSleep = proplists:get_value(reconnect_sleep, Args, 100),
    MaxQueueSize   = proplists:get_value(max_queue_size, Args, infinity),
    QueueBehaviour = proplists:get_value(queue_behaviour, Args, drop),
    start_link(Host, Port, Password, ReconnectSleep,
               MaxQueueSize, QueueBehaviour).
```

Would it be possible to add the `socket_options` (and `tls`) flag functionalities to `eredis_sub` as well?

**Comment by zuiderkwast** [comment]
Yes, of course we can add it.

It seems to be fairly trivial. The main problem is that there are no tests for `eredis_sub` at all and that the implementation in `eredis_sub_client` contains a lot of duplicated code from `eredis_client`. When we fixed things like error handling in eredis_client, we didn't touch `eredis_sub_client`, because we didn't need it (until now). I'd prefer that we do some refactoring to get rid of the duplicated code in `eredis_sub_client`, but I'm not sure if it's worth it or not.

**Comment by e-kmisk** [comment]
I don't know if there is an easy alternative to using eredis_sub in our legacy codebase, but there probably isn't.

So for us it'd be great to get these options ported from regular eredis. Regarding the duplications and tests, code quality improvements would be nice, though I suppose are not as urgent for us. We will anyway verify the behavior internally, at least in case of TCP errors.
