### ISSUE TITLE
Pubsub: Re-subscribe after reconnect

### ISSUE THREAD

**Issue by zuiderkwast** [Nordix/eredis#50]
Currently, we store a list of channels but automatic re-subscribe after reconnect is not implemented.

For backward compat: If the user subscribes explicitly after reconnect, we can be OK'd without sending the command to Redis.

We need to store the type of subscribe for each channel (SUBSCRIBE or PSUBSCRIBE) to be able to re-issue the same command.

**Comment by e-kmisk** [comment]
Hi, is there any progress on this issue?  We are still discussing but this is probably a must-have for us, because modifying the clients to consciously re-subscribe on reconnect is not preferred.

**Comment by zuiderkwast** [comment]
I haven't started working on it yet. Have you? :-)

**Comment by bjosv** [comment]
Now when Redis 7.0 is released the `SSUBSCRIBE` is an new animal at the zoo.
I guess this is not used by you yet @e-kmisk ? or is it planned?

**Comment by zuiderkwast** [comment]
I'm starting working on resubscribe now.

@bjosv I guess sharded pubsub (SSUBSCRIBE, SPUBLISH) will have to be a different feature, in eredis or in eredis_cluster. It has not been requested by anyone so far, AFAIK.

**Comment by e-kmisk** [comment]
> Now when Redis 7.0 is released the SSUBSCRIBE is an new animal at the zoo.

The main use case for that is high throughput. Currently the components that use PubSub have very little messages/sec traffic, so sharding for those is not needed.

So far I could not find any good reports online about performance of PubSub and Sharded PubSub when it comes to messages/sec throughput and CPU/memory/network load. If we wanted to run something with high throughput using PubSub we would first need to benchmark regular PubSub internally, and then if that is too slow then also benchmark the sharded version. I don't think that will happen soon.

> I guess sharded pubsub (SSUBSCRIBE, SPUBLISH) will have to be a different feature, in eredis or in eredis_cluster.

It would have to be in eredis_cluster since it's related to sharding and slots, I imagine. An SSUBSCRIBE may get a MOVED response, like regular DB reads/writes. Additionally if the shard/slot migrates later at runtime *after* initial subscription it would also need to be handled by the client.

**Comment by zuiderkwast** [comment]
Regarding the behaviour: Is it OK that messages on the form `{subscribed, Channel, ClientPid}` are delivered to the controlling process after reconnect? Currently, there is nothing that intercepts these messages. If we want seamless resubscribe, we'd have to intercept and silence those messages, i.e. have some flag for each channel we are auto-resubscribing to.

Regarding subscribing multiple times (e.g. automatic + manual) there is currently code and tests for this. The SUBSCRIBE and PSUBSCRIBE command is sent to the server, but the channel is not added to the state if it's already there. We could change that too if you prefer.

Any preferences here?

**Comment by e-kmisk** [comment]
>  Is it OK that messages on the form {subscribed, Channel, ClientPid} are delivered to the controlling process after reconnect?

Looks like our current code handles `{subscribed, ...}` only by invoking 
```erl
eredis_sub:ack_message(Client)
```
where Client is the Pid of the eredis_sub_client gen_server. Atm. I don't know if this behavior makes sense in our code, I don't understand fully what it's trying to do. If calling ack_message like that causes no problems then there's no problem to us if these are re-sent on reconnect, I guess.

> Regarding subscribing multiple times (e.g. automatic + manual) there is currently code and tests for this. The SUBSCRIBE and PSUBSCRIBE command is sent to the server, but the channel is not added to the state if it's already there. We could change that too if you prefer.

The question is whether Redis itself ignores duplicate SUBSCRIBE commands. I could see two things happening - either the published messages arrive in duplicates too (because we subscribed N times), or Redis itself ignores such re-subscriptions for us as nonsense.

I don't think this is documented on redis side what happens. I would assume the latter is what happens, because the former would be pretty baffling. If the Redis side ignores duplicates, I guess there is no need to discard it on client side and we can rely on thir behavior.

**Comment by zuiderkwast** [comment]
It's good that your client does `ack_message(Client)` for `{subscribe, _, _}` messages. `eredis_sub` will not send any pubsub message until it is acked. All messages on channels and all subscribe messages need to be acked, otherwise they're queued in the eredis_sub_client. Only messages like `eredis_connected` are sent directly and don't need to be acked, but it does no harm to ack them too.

However, I wonder if it's OK for other users. Is it a backward-incompatible change? If it is, then maybe it's better to silently catch the subscribed messages. On the other hand, it may be good for the client to know that it may have missed some messages from the time it got `{eredis_disconnected, Client}` until it gets `{subscribed, Channel, Client}` after reconnect.

Another option is to add configuration to disable auto-resubscribe. But I don't know if it's needed. The messages sent by `eredis_sub` are not very well documented at all. I'm leaning towards letting these messages be forwarded to the client and perhaps document it.

Redis doesn't send duplicate messages, but also doesn't fail if you send another SUBSCRIBE, so it does no harm. However, we could avoid sending it from eredis sub client.

**Comment by e-kmisk** [comment]
> However, I wonder if it's OK for other users. Is it a backward-incompatible change?

Maybe not strictly, but I wonder how many users were even prepared properly for the reconnect + re-subscribe scenario so far? I know our code wasn't at least (ie. it doesn't re-subscribe on reconnect, it even discarded the `{eredis_connected, ...}` messages). I don't think it was intuitive how eredis behaved, so I also don't think it's bad to change the behavior.

> Redis doesn't send duplicate messages, but also doesn't fail if you send another SUBSCRIBE, so it does no harm. However, we could avoid sending it from eredis sub client.

I doubt redis side will change this behavior so I suppose it's fine to rely on it.
